---
output:
  pdf_document: default
  html_document: default
---
```{r warning = FALSE, message = FALSE}
#load package
library(dplyr)
library(tidyr)
library(gtsummary)
library(labelled)
library(MASS)
library(stats)
library(ggplot2)
#library(effects)
library(car)
library(tibble)
```
```{r}
source("./function.R")
```


```{r}
#Load preprocessed data
#data_filter <- readRDS(file = "../output/data_preprocessed.rds")
#data_filter <- readRDS(file = "../output/data_preprocessed_edited.rds") # merge the myanmar and the hearing aid
#data_filter <- readRDS(file = "../output/data_preprocessed_mergeethnic.rds") # merge the myanmar 
#data_filter <- readRDS(file = "../output/data_preprocessed_mergehearing.rds") # merge the hearing aid

data_filter <- readRDS("../output/data_preprocessed_mergehearing_mergeethnic_remove66.rds")


```

```{r}
## define custom test
fisher.test.simulate.p.values <- function(data, variable, by, ...) {
  result <- list()
  test_results <- stats::fisher.test(data[[variable]], data[[by]], simulate.p.value = TRUE)
  result$p <- test_results$p.value
  result$test <- test_results$method
  result
}
```


```{r}
##table 1 and table 2

#temporary convert Phq91-9 to factor
data_filter_phq9asfactor <- data_filter
data_filter_phq9asfactor$phq9_1 <- factor(data_filter_phq9asfactor$phq9_1, levels = c("0","1","2","3"))
data_filter_phq9asfactor$phq9_2 <- factor(data_filter_phq9asfactor$phq9_2, levels = c("0","1","2","3"))
data_filter_phq9asfactor$phq9_3 <- factor(data_filter_phq9asfactor$phq9_3, levels = c("0","1","2","3"))
data_filter_phq9asfactor$phq9_4 <- factor(data_filter_phq9asfactor$phq9_4, levels = c("0","1","2","3"))
data_filter_phq9asfactor$phq9_5 <- factor(data_filter_phq9asfactor$phq9_5, levels = c("0","1","2","3"))
data_filter_phq9asfactor$phq9_6 <- factor(data_filter_phq9asfactor$phq9_6, levels = c("0","1","2","3"))
data_filter_phq9asfactor$phq9_7 <- factor(data_filter_phq9asfactor$phq9_7, levels = c("0","1","2","3"))
data_filter_phq9asfactor$phq9_8 <- factor(data_filter_phq9asfactor$phq9_8, levels = c("0","1","2","3"))
data_filter_phq9asfactor$phq9_9 <- factor(data_filter_phq9asfactor$phq9_9, levels = c("0","1","2","3"))
```

```{r}
table1 <- 
  data_filter_phq9asfactor %>%
  tbl_summary()

table2 <- 
  data_filter_phq9asfactor %>%
  tbl_summary(by = phq_9_cat) %>%
  add_p(
  test = list(all_categorical() ~ "fisher.test.simulate.p.values")  # this applies the custom test to all categorical variables
)  %>%
  add_overall()
```


```{r}
table1
table2
```


```{r}
data_filter %>% ggplot(aes(x = phq_9_cat)) + geom_bar()

data_filter %>% group_by(phq_9_cat) %>%
  summarise(frequency = n())
```

```{r}
data_filter %>%
  ggplot(aes(x = phq_9_score)) +
  geom_histogram(binwidth = 1) +
  stat_bin(binwidth = 1, geom = "text", aes(label = ..count..), vjust = -0.5) +
  labs(y = "The number of patient", x = "PHQ-9 score") +
  theme_pubr()


data_filter %>% group_by(phq_9_score) %>%
  summarise(frequency = n())
```
```{r}
data_filter %>% ggplot(aes(x = phq9_9)) + geom_bar()

data_filter %>% group_by(phq9_9) %>%
  summarise(frequency = n())
```
```{r}
data_filter %>% ggplot(aes(x = factor(phq9_9), y = phq_9_score)) + geom_count() +
  labs(y = "The number of patient", x = "PHQ-9 score: 9th item") +
  theme_pubr()
```
```{r}
data_filter %>% ggplot(aes(x = factor(phq9_9), y = phq_9_score)) + geom_violin() +
  labs(y = "The number of patient", x = "PHQ-9 score: 9th item") +
  theme_pubr()
```

```{r}
data_filter %>% ggplot(aes(x = factor(phq9_9), y = phq_9_score)) + geom_boxplot() +
  labs(y = "The number of patient", x = "PHQ-9 score: 9th item") +
  theme_pubr()
```

```{r}
#test whether phq9_9 is related to ph9_9_score using t-test

t.test(data_filter[data_filter$phq9_9 == 1,]$phq_9_score,data_filter[data_filter$phq9_9 == 0,]$phq_9_score)
```
```{r}
## Explore each question of PHQ9

for (i in 1:9) {
  print(paste0("PHQ9_",i,": ",
               attributes((data_filter[,32:40])[,i,drop = TRUE])$label))
}

```
```{r}
#convert wide to long to be used in ggplot
data_long <- gather(data_filter, phq, score, phq9_1:phq9_9, factor_key=TRUE)
```


```{r}
data_long %>% ggplot(aes(x=score)) + geom_histogram() + facet_wrap(~phq)
```

#Check before analyisis
```{r}
#Check for Multicollinearity
```


```{r}
column_to_excludes <- c("WeightofPatient","HeightofPatient",
                        "phq9_1","phq9_2","phq9_3","phq9_4","phq9_5","phq9_6","phq9_7","phq9_8","phq9_9","phq_9_cat","phq_9_score")

mix_assoc_result <- mixed_assoc(data_filter[,!colnames(data_filter) %in% column_to_excludes])

```

```{r}
mix_assoc_result %>%
  dplyr::select(-complete_obs_pairs, -complete_obs_ratio) %>%
  filter(x != y) %>%
  filter(assoc != 0) %>%
  arrange(desc(abs(assoc))) %>%
  filter(row_number() %% 2 == 1) %>%
  group_by(type) %>%
  slice_max(order_by = abs(assoc), n = 10) %>%
  ungroup()
```

```{r}
library(corrplot)
mix_assoc_result %>%
    dplyr::select(x,y,assoc) %>%
    spread(y, assoc) %>%
    column_to_rownames("x") %>%
    as.matrix %>%
    corrplot(tl.cex = 0.6)
```

<!-- ```{r} -->
<!-- require(corrr) -->
<!-- mix_assoc_result %>% -->
<!--     dplyr::select(x,y,assoc) %>% -->
<!--     spread(y, assoc) %>% -->
<!--     column_to_rownames("x") %>% -->
<!--     as.matrix %>% -->
<!--     as_cordf %>% -->
<!--     network_plot(min_cor = 0.05,legend = "full") + geom_text(size = 0.1) -->
<!-- ``` -->


```{r}
#explore vif & gvif

column_to_excludes <- c("WeightofPatient","HeightofPatient",
                        "phq9_1","phq9_2","phq9_3","phq9_4","phq9_5","phq9_6","phq9_7","phq9_8","phq9_9","phq_9_cat")


lm_model <- lm(phq_9_score ~ ., data = data_filter[,!colnames(data_filter) %in% column_to_excludes])

vif(lm_model)
```

```{r}
## Try the automatic selection by collinear 
library(collinear)
column_to_excludes_initial <- c("WeightofPatient","HeightofPatient",
                        "phq9_1","phq9_2","phq9_3","phq9_4","phq9_5","phq9_6","phq9_7","phq9_8","phq9_9","phq_9_cat","phq_9_score")

response_choices <- c("phq_9_cat","phq_9_score")
selected_response <- response_choices[2]

column_to_excludes <- setdiff(column_to_excludes_initial,selected_response)

predictors <- setdiff(setdiff(colnames(data_filter),column_to_excludes),selected_response)
```


```{r}
#for linear
selected_predictors_no_preference <- collinear(
  df = data_filter[,!colnames(data_filter) %in% column_to_excludes],
  response = selected_response,
  predictors = predictors,
  preference_order = NULL,
  max_cor = 0.5,
  max_vif = 2.5,
  encoding_method = "mean"
)


preference_rsquared <- preference_order(
  df = data_filter[,!colnames(data_filter) %in% column_to_excludes],
  response = selected_response,
  predictors = predictors,
  f = f_rsquared,
  workers = 4 #requires package future and future.apply for more workers
)

selected_predictors_with_preference <- collinear(
  df = data_filter[,!colnames(data_filter) %in% column_to_excludes],
  response = selected_response,
  predictors = predictors,
  preference_order = preference_rsquared,
  max_cor = 0.5,
  max_vif = 2.5,
  encoding_method = "mean"
)
```


```{r}
selected_predictors_no_preference
selected_predictors_with_preference
```
```{r}
#for logistic

selected_predictors_no_response <- cor_select(
  df = data_filter[,!colnames(data_filter) %in% column_to_excludes],
  predictors = predictors,
  preference_order = preference_rsquared,
  max_cor = 0.5
)

selected_predictors_no_response
```



```{r}
# Exclude specified columns
column_to_excludes <- c("WeightofPatient", "HeightofPatient",
                        "phq9_1", "phq9_2", "phq9_3", "phq9_4", "phq9_5", "phq9_6", "phq9_7", "phq9_8", "phq9_9", "phq_9_cat", "phq_9_score")
full_var <- setdiff(colnames(data_filter), column_to_excludes)

# Create the initial data frame
df_collinear_remove <- data.frame(original = full_var,
                        collinear_linear_with_preference = full_var,
                        collinear_linear_no_preference = full_var,
                        collinear_no_response = full_var)

# Helper function to replace variables with NA
replace_with_na <- function(df, col_name, exclude_vars) {
  vars_to_replace <- setdiff(full_var, exclude_vars)
  df[[col_name]] <- sapply(df[[col_name]], function(x) if (x %in% vars_to_replace) NA_character_ else x)
  return(df)
}

# Apply the helper function for each scenario
df_collinear_remove <- replace_with_na(df_collinear_remove, "collinear_linear_with_preference", selected_predictors_with_preference)
df_collinear_remove <- replace_with_na(df_collinear_remove, "collinear_linear_no_preference", selected_predictors_no_preference)
df_collinear_remove <- replace_with_na(df_collinear_remove, "collinear_no_response", selected_predictors_no_response)

```
```{r}
df_collinear_remove %>%
  filter(if_any(everything(), is.na))
```

##Multiple linear regression

```{r warning = FALSE, message = FALSE}
# Multiple linear regression
column_to_excludes <- c("WeightofPatient","HeightofPatient",
                        "phq9_1","phq9_2","phq9_3","phq9_4","phq9_5","phq9_6","phq9_7","phq9_8","phq9_9","phq_9_cat")


lm_model <- lm(phq_9_score ~ ., data = data_filter[,!colnames(data_filter) %in% column_to_excludes])

# Print the summary of the model
summary(lm_model)
```
```{r warning = FALSE, message = FALSE}
lm_tbl <- lm_model %>% tbl_regression()
lm_tbl
```



# Ordered logistic regression
```{r}
# Ordered logistic regression
column_to_excludes <- c("WeightofPatient","HeightofPatient",
                        "phq9_1","phq9_2","phq9_3","phq9_4","phq9_5","phq9_6","phq9_7","phq9_8","phq9_9","phq_9_score")



ordered_logistic_model <- polr(phq_9_cat ~ ., data = data_filter[,!colnames(data_filter) %in% column_to_excludes],Hess = TRUE)

# Print the summary of the model
summary(ordered_logistic_model)
```
```{r }
ordered_logistic_tbl <- ordered_logistic_model %>% tbl_regression(exponentiate = TRUE)
ordered_logistic_tbl
```


```{r warning = FALSE, message = FALSE}
Anova(ordered_logistic_model)
```



#Binary logistic regression
```{r warning = FALSE, message = FALSE}
#Binary logistic regression only for the phq9-9 question 
column_to_excludes <- c("WeightofPatient","HeightofPatient",
                        "phq9_1","phq9_2","phq9_3","phq9_4","phq9_5","phq9_6","phq9_7","phq9_8","phq_9_score","phq_9_cat")

column_to_excludes <- c("WeightofPatient","HeightofPatient","phq_9_score","phq_9_cat")

binary_logistic_model <- glm(phq9_9 ~ ., family = binomial(), data = data_filter[,!colnames(data_filter) %in% column_to_excludes])

summary(binary_logistic_model)
```

```{r warning = FALSE, message = FALSE}
binary_logistic_tbl <- binary_logistic_model %>% tbl_regression(exponentiate = TRUE)
binary_logistic_tbl
```

#Export data
```{r}
table1 %>% as_hux_xlsx("../output/table_1.xlsx")
table2 %>% as_hux_xlsx("../output/table_2.xlsx")

lm_tbl %>% as_hux_xlsx("../output/multivariated_linear.xlsx")
ordered_logistic_tbl %>% as_hux_xlsx("../output/phd9_cat_ordered_logistic.xlsx")
binary_logistic_tbl %>% as_hux_xlsx("../output/phq9_9th_logistic.xlsx")
```


<!-- #Additional analyisis -->
<!-- ```{r} -->
<!-- library(glmnet) -->
<!-- library(caret) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- # Multiple linear regression -->
<!-- column_to_excludes <- c("WeightofPatient","HeightofPatient", -->
<!--                         "phq9_1","phq9_2","phq9_3","phq9_4","phq9_5","phq9_6","phq9_7","phq9_8","phq9_9","phq_9_cat") -->


<!-- # Fit a Ridge regression model -->
<!-- ridge_model <- glmnet(x = data_filter[,!colnames(data_filter) %in% column_to_excludes], y = data_filter$phq_9_score, alpha = 0)  # alpha = 0 for Ridge regression -->
<!-- print(ridge_model) -->

<!-- # Fit a LASSO model -->
<!-- lasso_model <- cv.glmnet(x = data_filter[,!colnames(data_filter) %in% column_to_excludes], y = data_filter$phq_9_score,  alpha = 1)  # alpha = 1 for LASSO -->
<!-- print(lasso_model) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- lasso_model <- glmnet(x = data_filter[,!colnames(data_filter) %in% column_to_excludes], y = data_filter$phq_9_score,  alpha = 1) -->
<!-- lasso_model <- cv.glmnet(X_matrix, y_numeric, family = "multinomial", alpha = 1) -->
<!-- ``` -->

